toad.jar : Asm.class \
	Help.class \
	ShuffleApplet.class \
	Shuffle.class \
	Tiling.class
	jar cf toad.jar *.class

Asm.class : Asm.java
	javac *.java

Help.class : Help.java
	javac *.java

ShuffleApplet.class : ShuffleApplet.java
	javac *.java

Shuffle.class  : Shuffle.java
	javac *.java

Tiling.class : Tiling.java
	javac *.java
