#!/bin/sh
cd "$(dirname "$0")/.."
git ls-files | grep '\.html$' | grep -v 'mathapplets/' | while IFS= read -r line; do
    if [ "$line" = SSL/Apollonian-Gasket/2003-10-30-apollonian/2003-10-30-apollonian.html ]; then
        continue
    fi
    X="$(tidy -q -e $line 2>&1)"
    if [ "$X" ]; then
        echo $line
        echo "$X"
        echo
    fi
done

