#! /usr/bin/env python

import sys,re, subprocess

empty = re.compile('^\\s*$')
def headtail(path):
    with open(path) as f:
        lines = f.readlines()
    idx = next(i for i, line in enumerate(lines) if empty.match(line))
    return (lines[:idx], lines[idx:])

def todict(head):
    return dict(line.rstrip().split('=', 1) for line in head)

keys = [
  'COPYRIGHT',
  'TITLE',
  'DATE',
  'POSTID',
  'CATEGORIES',
  'MODE',
  'SUMMARY',
]

def htmlToMarkdown(src):
    proc = subprocess.Popen(
        ['node', 'src/turndown.js'],
        stdout=subprocess.PIPE,
        stdin=subprocess.PIPE)
    proc.stdin.write(src)
    proc.stdin.close()
    result = proc.stdout.read()
    proc.wait()
    return result

def proc(path):
    head, tail = headtail(path)
    d = todict(head)
    if d['MODE'] != 'htmldiv':
        return
    markdown = htmlToMarkdown(''.join(tail))
    if not markdown:
        return
    d['MODE'] = 'markdown'   
    with open(path, 'w') as o:
        for key in keys:
            if key in d:
                o.write('%s=%s\n' %(key, d[key]))
        o.write('\n')
        o.write(markdown)
        if not markdown.endswith('\n'):
            o.write('\n')

if __name__ == '__main__':
    for path in sys.argv[1:]:
        sys.stdout.write(path + '\n')
        proc(path)
