#! /bin/sh
SDIR="$(dirname "$0")"
DIR="${SDIR}/BlogSrc"
BIGGEST=0
for x in $(sed -n 's/^POSTID=//p' "$DIR"/*); do
  if [ "$x" -gt $BIGGEST ] 2> /dev/null; then
     BIGGEST=$x
  fi
done
POSTID=$(( $BIGGEST + 1 ))
#DATE="$(date '+%Y-%m-%d %H:%M:%S %z (%Z)')"
DATE="$("${SDIR}/isodate.py")"
FILE=$DIR/$(date '+%Y-%m-%d')-${POSTID}.md
echo $FILE
cat << EOM > $FILE
AUTHOR=Hal Canary
TITLE=
DATE=$DATE
POSTID=$POSTID
CATEGORIES=
SUMMARY=
EOM
