#!/usr/bin/env python
# coding=utf-8

import sys, os, math, subprocess, re, datetime, tempfile, hashlib, shutil

BASE_DIR = 'vv'
URL_BASE = 'https://halcanary.org'

MARKDOWN_CMD = ['cmark']
if float(re.sub(r'cmark (\d+\.\d+)\..*', r'\1', subprocess.check_output(['cmark', '--version']), flags=re.S)) >= 0.29:
    MARKDOWN_CMD = ['cmark', '--unsafe']

current_year = datetime.date.today().year
first_year = 1997

def get_years():
    return '{:04d}-{:04d}'.format(first_year, current_year)

with open(os.path.dirname(__file__) + '/style.css') as f:
    style = re.sub(r'(^|:|;|{)\s+', r'\1', f.read(), flags=re.M).strip()

header = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<link rel="icon" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACAAQAAAADrRVxmAAAACXBIWXMAAAMfAAADHwHmEQywAAAAGXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAAVZJREFUSMfd1EuOwyAMAFAQ0rAZNUfIUTga5GbsZtkrcINhyQLBYMgHG6ZddJcoSpOXDzY2ZZls7F5Q9iAzhyu/XsAomCm4AdRHYPUUNAH7GTgdRbZd+k6FCZgGZQPw/DV45dgIWw+rc3rrRvGrHcBrjmDzqocAIBCIsr+ERcYFwYNAfMj0QPC9pC+JIWNgpfJvQGXTQwJYCFgMegSHIWPIA/DaplO49UIuEy7qUR5gWakJHA+oXZhNZYBYQNQnlgaBKSthrRjRwJXfcu+ZA28A5fmF7yXWwKg+BgB9AJyxPtgGib8FQSCKjEcZQR7XqUUaTgiCgJME9vRPMEwREJk+McCKodUBDUvjiDTSfU4v2NPvwCqc7QHif3Bz6Ga9vZIYga5yVs9rO1Qf+uOnSw6yhnKu2Yurx+C/Ru8TVLuQl9HPtmx9CqCvTlYwxxz3eqhv3Htl/wEokJpySHNGkgAAAABJRU5ErkJggg==">
<style>
{style}
</style>
</head>
<!-- Copyright {years} Hal Canary. ALL RIGHTS RESERVED. -->
<body>
"""

top_posts_header = """
<header>
<h1>Voder-Vocoder</h1>
</header>

<div class="centered" role="contentinfo">The Log of Hal Canary</div>

<div role="search">
<button onclick="this.style.display='none';document.getElementById('search-hco').style.display='block';">Search</button>
<div id="search-hco" style="display:none;text-align:right">
<form method="get" action="https://www.google.com/search">
<input name="domains" value="halcanary.org" type="hidden">
<input name="sitesearch" value="halcanary.org" type="hidden">
<input id="search" name="q" size="30" maxlength="255" aria-labelledby="submitter">
<input value="Search" type="submit" id="submitter">
</form>
</div>
</div>

<hr>
"""
top_posts_footer = """
<nav aria-label="External Navigation"><p class="centered">(<a href="archives/">all posts</a>)</p></nav>
</body>
</html>
"""

def hashpath(path):
    if path is None:
        return None
    h = hashlib.sha256()
    with open(path,'r') as f:
        data = f.read(h.block_size)
        while data != '':
            h.update(data)
            data = f.read(h.block_size)
    return h.digest()

def mkdirs(path):
    try:
        os.makedirs(path)
    except:
        pass

def lcr(left, center, right):
    left   = '<p>{}</p>'.format(left) if left else '&nbsp;'
    center = '<p>{}</p>'.format(center) if center else '&nbsp;'
    right  = '<p>{}</p>'.format(right) if right else '&nbsp;'
    return '''<div class="lcr">
  <div>{}</div>
  <div class="centered">{}</div>
  <div class="rightside">{}</div>
</div>'''.format(left, center, right)

class UpdatingFile(object):
    def __init__(self, path):
        mkdirs(os.path.dirname(path))
        self.path = path
        fd, self.tempfilepath = tempfile.mkstemp()
        self.o = os.fdopen(fd, "w")

    def __del__(self):
        self.close()

    def __enter__(self):
        return self

    def __exit__(self, type, value, traceback):
        if self.close():
            sys.stdout.write('modified %s\n' % self.path)

    def close(self):
        if self.o is not None:
            self.o.close()
            self.o = None
            if (not os.path.isfile(self.path)) or (
                hashpath(self.tempfilepath) !=
                hashpath(self.path)):
                if shutil:
                    shutil.copyfile(self.tempfilepath, self.path)
                os.remove(self.tempfilepath)
                return True
            else:
                if self.tempfilepath is not None:
                    os.remove(self.tempfilepath)
                return False

    def write(self,*args, **kwargs):
        (self.o if self.o is not None else sys.stderr).write(*args, **kwargs)


class Post(object):
    @staticmethod
    def markdown(inf):
        try:
            subproc = subprocess.Popen(MARKDOWN_CMD, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
        except OSError:
            sys.stderr.write('\n%r FAILED.\n\n' % MARKDOWN_CMD)
            sys.exit(1)
        shutil.copyfileobj(inf, subproc.stdin)
        subproc.stdin.close()
        s = subproc.stdout.read()
        subproc.wait()
        return s

    @staticmethod
    def write(o, post_info, level, identifier=None):
        category_fmt = '<a href="/{1}/category/{0}/">#{0}</a>'
        categories = '; '.join(category_fmt.format(cat, BASE_DIR) for cat in post_info['category_list'])
        # keys = [ 'src', 'permalinkpart', 'title', 'summary', 'date', 'category_list', 'post' ]
        summ = '    <p>{}</p>'.format(post_info['summary']) if post_info['summary'] else ''
        post_template = """
<article id="{fragment}">
  <header>
    <!-- SRC= {src} -->
    <h{level} class="blogtitle">{title}</h{level}>
{summ}
    <div class="byline plainlink">
      <div>
          Hal Canary<br>
          {date}<br>
          <a href="/{permalinkpart}">{URL_BASE}/{permalinkpart}</a><br>
          {categories}
      </div>
    </div>
  </header>
  <div class="content">
{post}
  </div>
</article>
<hr>
"""
        o.write(post_template.format(level=level, categories=categories, summ=summ,
                                     URL_BASE=URL_BASE, **post_info))

    def __init__(self, path):
        # Required:
        #    TITLE
        #    DATE
        #    POSTID
        # Suggested:
        #    SUMMARY
        #    CATEGORIES
        #    MODE
        # Everything else is ignored
        if not os.path.isfile(path):
            raise Exception(path + " is not a file")

        self.src = os.path.basename(path)
        self.category_list = []
        self.summary = ''
        self.date = None
        self.day = None
        self.month = None
        self.permalinkpart = None
        self.post = None
        self.title = None
        self.year = None
        self.next = None
        self.prev = None

        postid = None
        mode = 'markdown'
        with open(path,'r') as f:
            while True:
                sline = f.readline().strip()
                if sline == '':
                    break
                if '=' not in sline:
                    sys.stderr.write(sline + '\n') # error
                    continue
                key, value = sline.split('=',1)
                value = value.strip()
                if value == '':
                    continue
                if key == 'TITLE':
                    self.title = value
                elif key == 'DATE':
                    self.date = value
                elif key == 'POSTID':
                    postid = value
                elif key == 'SUMMARY':
                    self.summary = value
                elif key == 'CATEGORIES':
                    self.category_list = filter(len, value.split(';'))
                elif key == 'MODE':
                    mode = value
                elif key != 'COPYRIGHT':
                    sys.stderr.write('%s: %r=%r\n' % (path, key, value))

            if mode.lower() == 'markdown':
                self.post = Post.markdown(f).rstrip()
            else:
                self.post = f.read().rstrip()

        if self.date is None:
            raise Exception('DATE missing ({})'.format(path))
        if postid is None:
            raise Exception('POSTID missing ({})'.format(path))
        if self.title is None:
            raise Exception('TITLE missing ({})'.format(path))

        if not self.category_list :
            self.category_list.append('uncategorized')

        timestamp = datetime.datetime.strptime(self.date.split()[0], '%Y-%m-%d').date()
        self.year  = timestamp.year
        self.month = timestamp.month
        self.day   = timestamp.day
        self.postid = postid

        self.permalinkpart = '{:s}/{:04d}/{:02d}/{:02d}/{:s}/'.format(BASE_DIR, self.year, self.month, self.day, postid)
        self.fragment = '{:04d}_{:02d}_{:02d}_{:s}'.format(self.year, self.month, self.day, postid)

    def write_to_file(self, output_path):
        def linker(post):
            return '(<a href="/{}">{}</a>)'.format(post.permalinkpart, post.title) if post else None

        up = '(<a href="/{}/archives/">back</a>)'.format(BASE_DIR)
        with UpdatingFile(output_path) as o:
            o.write(header.format(title='Voder-Vocoder: ' + self.title, style=style, years=get_years()))
            Post.write(o, vars(self), 1)
            o.write('<nav>\n')
            o.write(lcr(linker(self.prev), up, linker(self.next)))
            o.write('\n</nav>\n</body>\n</html>')

class RecentPosts(object):
    def __init__(self):
        self.posts = []
    def addPost(self, post):
        self.posts.append(post)
    def close(self):
        with UpdatingFile('{}/index.html'.format(BASE_DIR)) as o:
            o.write(header.format(style=style, title='Voder-Vocoder', years=get_years()))
            o.write(top_posts_header)
            o.write('<nav>\n<ul class="flat">\n')
            for post in self.posts:
                o.write('<li><a href="#{}">{}</a></li>\n'.format(post.fragment, post.title))
            o.write('</ul>\n</nav>\n<hr>\n<div role="main">\n')
            for post in self.posts:
                Post.write(o, vars(post), 2)
            o.write('</div>\n')
            o.write(top_posts_footer)

def writeIndex(loc, title, post_list, prev_next):
    posts = index_by_keyfn(post_list, lambda p: [p.year])
    with UpdatingFile(loc) as o:
        o.write(header.format(style=style, title=title, years=get_years()))
        o.write('\n<h1>{}</h1>\n\n'.format(title.replace('\n', '<br>')))
        o.write('<div role="main">\n')
        for year in sorted(posts.keys(), reverse=True):
            year_posts = posts[year]
            if len(posts) > 1:
                o.write('<h2>{year:d}</h2>\n'.format(year=year))
            o.write('<ul>\n')
            for post in year_posts:
                s = '  <div>{}</div>'.format(post.summary) if post.summary else ''
                fmt = '<li>\n  <a href="/{permalinkpart}">{title}</a>\n  {date}\n{s}\n</li>\n'
                o.write(fmt.format(s=s, **vars(post)))
            o.write('</ul>\n\n')
        o.write('</div>\n')
        previ, nexti = prev_next
        o.write('<hr>\n')
        up = '(<a href="../">UP</a>)'

        def linker(key):
            if not key:
                return None
            if not isinstance(key, tuple):
                key = (key,)
            k = tuple('{:02d}'.format(e) for e in key)
            u, v = '/'.join(k), '-'.join(k)
            return '(<a href="/{}/{}/">{}</a>)'.format(BASE_DIR, u, v)
        o.write('<nav>\n')
        o.write(lcr(linker(previ), up, linker(nexti)))
        o.write('\n</nav>\n\n</body>\n</html>\n')

def listdir(path, reverse=False):
    assert os.path.isdir(path)
    files = os.listdir(path)
    files.sort(reverse=reverse)
    for fn in files:
        yield os.path.join(path, fn)

def makelinks(values):
    result = dict()
    sv = sorted(values)
    for i, v in enumerate(sv):
        result[v] = ( sv[i - 1] if i > 0 else None,
                      sv[i + 1] if i + 1 < len(sv) else None )
    return result

def index_by_keyfn(posts, keys_fn):
    result = dict()
    for post in posts:
        for key in keys_fn(post):
            result.setdefault(key, []).append(post)
    return result

if __name__ == '__main__':
    src_dir = os.path.abspath(os.path.dirname(__file__))
    target_location = os.path.join(src_dir, os.pardir)
    source_location = os.path.join(src_dir, 'BlogSrc')

    directory = source_location
    os.chdir(target_location)
    assert os.path.isdir(directory)
    recentPosts = RecentPosts()
    all_posts = []
    for path in listdir(directory, reverse=True):
        if path[-1] == '~':
            continue
        if os.path.isfile(path):
            all_posts.append(Post(path))
        else:
            sys.stderr.write("???? %s\n" % path)

    for i, post in enumerate(all_posts):
        post.next = all_posts[i - 1] if i > 0 else None
        post.prev = all_posts[i + 1] if i + 1 < len(all_posts) else None
        if i < 10:
            recentPosts.addPost(post)

    posts_by_year     = index_by_keyfn(all_posts, lambda p: [p.year])
    posts_by_month    = index_by_keyfn(all_posts, lambda p: [(p.year, p.month)])
    posts_by_day      = index_by_keyfn(all_posts, lambda p: [(p.year, p.month, p.day)])
    posts_by_category = index_by_keyfn(all_posts, lambda p: p.category_list)

    first_year = min(posts_by_year.keys())

    year_links = makelinks(posts_by_year.keys())
    for year, posts in posts_by_year.items():
        writeIndex('{}/{:04d}/index.html'.format(BASE_DIR, year),
                   'Voder-Vocoder Archive\n{:04d}'.format(year),
                   posts,
                   year_links[year])

    month_links = makelinks(posts_by_month.keys())
    for (year, month), posts in posts_by_month.items():
        writeIndex('{}/{:04d}/{:02d}/index.html'.format(BASE_DIR, year, month),
                   'Voder-Vocoder Archive\n{:04d}-{:02d}'.format(year, month),
                   posts,
                   month_links[(year, month)])

    day_links = makelinks(posts_by_day.keys())
    for (year, month, day), posts in posts_by_day.items():
        writeIndex('{}/{:04d}/{:02d}/{:02d}/index.html'.format(BASE_DIR, year, month, day),
                   'Voder-Vocoder Archive\n{:04d}-{:02d}-{:02d}'.format(year, month, day),
                   posts,
                   day_links[(year, month, day)])

    for cat, posts in posts_by_category.items():
        writeIndex('{}/category/{}/index.html'.format(BASE_DIR, cat),
                   'Voder-Vocoder Archive\n#{}'.format(cat),
                   posts,
                   (None, None))

    writeIndex('{}/archives/index.html'.format(BASE_DIR),
               'Voder-Vocoder Archives',
                all_posts,
                (None, None))

    for post in all_posts:
        post.write_to_file(post.permalinkpart + 'index.html')

    recentPosts.close()

    with UpdatingFile('{}/category/index.html'.format(BASE_DIR)) as o:
        o.write(header.format(title='categories', style=style, years=get_years()))
        o.write(
            '<h1><a href="/{}/" class="hiddenlink">Voder-Vocoder</a> Archive by Category</h1>'.format(
            BASE_DIR))
        o.write("\n\n<ul>\n")
        for cat, posts in sorted(posts_by_category.items()):
            o.write('<li><a href="/{0}/category/{1}/">#{1} ({2})</a></li>\n'.format(
                    BASE_DIR, cat, len(posts)))
        o.write(('</ul>\n<hr>\n' +
                '<p class="centered"><a href="/{}/">BACK</a></p>\n' +
                '</body>\n</html>\n').format(BASE_DIR))

