#! /usr/bin/env python3
# coding=utf-8

import os
import sys
import html

def get_files(directory):
    for subdir, _, filenames in os.walk(directory):
        for filename in filenames:
            yield os.path.join(subdir, filename)

def main():
    TEMPLATE = '''<!doctype html>
<html lang="en">
<meta charset="UTF-8">
<meta http-equiv="refresh" content="0; url={0}">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{1}</title>
<body><a style="overflow-wrap:break-word" href="{1}">{1}</a></body>
</html>
'''
    ROOT = 'https://halcanary.org/'
    BASE_DIR = os.path.dirname(__file__) + '/../'
    REDIRECTS_DIR = BASE_DIR + 'src/redirects'
    for redirects_file in get_files(REDIRECTS_DIR):
        key = os.path.relpath(redirects_file, REDIRECTS_DIR)
        with open(redirects_file) as f:
            value = f.read().strip()
        path = os.path.normpath(BASE_DIR + key)
        if not os.path.exists(path):
            os.makedirs(path)
        value = html.escape(value)
        short = value.replace(ROOT, '/', 1) if value.startswith(ROOT) else value
        with open(path + '/index.html', 'w') as o:
            o.write(TEMPLATE.format(value, short))
        sys.stdout.write(key + '\n')

if __name__ == '__main__':
    main()
