#!/usr/bin/env python
# coding=utf-8

import sys, os, subprocess, datetime, base64, re

PY3 = sys.version_info > (3,)

def find_files(d):
    return (os.path.relpath(os.path.join(ds, n), d) for ds, _, ns in os.walk(d) for n in ns)

def write_file(filepath, filecontent):
    directory = os.path.dirname(filepath)
    if os.path.exists(filepath):
        if filecontent == read_file(filepath):
            return
    if not os.path.exists(directory):
        os.makedirs(directory)
    kwargs = dict(encoding='utf-8') if PY3 else dict()
    with open(filepath, 'w', **kwargs) as o:
        o.write(filecontent)

def read_file(filepath, binary=False):
    assert os.path.exists(filepath)
    kwargs = dict(encoding='utf-8') if PY3 and not binary else dict()
    with open(filepath, 'rb' if binary else 'r', **kwargs) as f:
        return f.read()

page_template = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- Copyright 1997-2020 Hal Canary. ALL RIGHTS RESERVED. -->
<title>{title}</title>
<link rel="icon" href="data:image/png;base64,{icon}">
<link rel="stylesheet" type="text/css" href="/styles/scrapple-from-the-apple.css">
<style>
@media screen {{ body{{
    max-width: 35em;
    margin: 22px auto 64px auto;
    padding: 0 8px;
}} }}
body {{
    color: #000000;
    background-color: #ffffff;
    background-image: none;
    text-align: initial;
}}
</style>
</head>

<body>

<h1><a href="/" class="hiddenlink">
{svg}
</a></h1>

<nav class="section"><p><a href="/">Home</a></p></nav>

{content}

<div class="section">
<p class="centered">Copyright 1997-2013 by Hal Canary.<br>
<i>mailto: halcanary at gmail dot com</i><br>
<a href="https://halcanary.org"><i>http://halcanary.org</i></a></p>
</div>

</body>
</html>
"""

def main():
    root = os.path.dirname(__file__) + '/../'
    style = re.sub(r'(^|:)  *', r'\1', read_file(root + 'src/style.css'), flags=re.M).strip()
    years = '1997-{:04d}'.format(datetime.date.today().year)
    icon = base64.b64encode(read_file(root + 'images/2020-HWC3-favicon.png', binary=True))
    if (sys.version_info > (3, 0)):
        icon = str(icon, encoding='us-ascii')
    svg = read_file(root + 'src/hal_canary_3.svg').strip()

    suffix = '.html'
    for path in find_files(root + 'src/tmp-pages'):
        if not path.endswith(suffix):
            continue
        dst = path[:-len(suffix)]
        sys.stdout.write(dst +'\n')
        src = 'src/tmp-pages/%s.html' % dst
        assert os.path.exists(src)
        content = read_file(root + src).strip()
        write_file(root + dst + '/index.html', page_template.format(
            content=content,
            title='World of Hal Canary',
            svg=svg,
            icon=icon))

if __name__ == '__main__':
    main()
