#!/usr/bin/env python
# coding=utf-8

import datetime
import os
import re
import sys

import wohc

def find_files(d):
    return (os.path.relpath(os.path.join(ds, n), d) for ds, _, ns in os.walk(d) for n in ns)

def get_first_h1(s):
    m = re.search("(?s)<h1>(.*?)</h1>", s)
    return m.group(1) if m else None

page_template = """<!DOCTYPE html>
<html lang="en">
{head}
<body>
<div class="tophead" role="banner">
{svg}
</div>
<div role="main">
{content}
</div>
</body>
</html>
"""
root_template = """<!DOCTYPE html>
<html lang="en">
{head}
<body>
<header>
<h1>
{svg}
</h1>
</header>
<div role="main">
{content}
</div>
</body>
</html>
"""

def main():
    years = '1997-{:04d}'.format(datetime.date.today().year)
    suffix = '.md'
    src_directory = wohc.SRC + '/pages'
    for path in find_files(src_directory):
        if not path.endswith(suffix):
            continue
        dst = '/{}/index.html'.format(path[:-len(suffix)])
        process(os.path.join(src_directory, path), dst, years)
    process(wohc.SRC + '/index.md', '/index.html', years, True)
    process(wohc.SRC + '/resume.md', '/Hal_Canary_Resume.html', years)

def process(src, dst, years, root=False):
    assert os.path.exists(src)
    content = wohc.pipe_process(wohc.read_file(src), wohc.MARKDOWN_CMD)
    title = 'Hal W. Canary, III' if root else get_first_h1(content)
    assert title
    svg_value = wohc.SVG
    if any(dst.startswith(d) for d in ['/SSL/', '/mathapplets/', '/u/']):
        svg_value = ''
    head = wohc.HEAD.format(icon=wohc.ICON, style=wohc.STYLE, title=title, years=years)
    template = root_template if root else page_template
    page = template.format(head=head, svg=svg_value, content=content)
    if wohc.write_file(wohc.ROOT + dst, page):
        sys.stdout.write(dst +'\n')

if __name__ == '__main__':
    main()
