rotor.jar: GroveApplet.class Grove.class
	jar -cvf grove.jar *.class

ConsoleGrove.class: ConsoleGrove.java
	javac ConsoleGrove.java

GroveApplet.class:  GroveApplet.java
	javac GroveApplet.java 

Grove.class:  Grove.java
	javac Grove.java 

MathSystem.class:   MathSystem.java  
	javac MathSystem.java  





